name: Generate Snake Animation

on:
  schedule: # Exécuter toutes les 12 heures
    - cron: "0 */12 * * *" 
  workflow_dispatch:

jobs:
  build:
    name: Update Snake Animation
    runs-on: ubuntu-latest

    steps:
      # Action pour générer le SVG de l'animation Snake
      - name: Generate Snake SVG
        uses: Platane/snk@v2
        with:
          github_user_name: TomDMonkey  # Remplace par ton nom d'utilisateur GitHub
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publier le fichier SVG sur la branche output
      - name: Deploy Snake to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
